language: c

os:
    - linux

dist: trusty
sudo: required

compiler:
    - clang
    - gcc

before_install:
    - wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz
    - tar xzf SDL2-2.0.5.tar.gz

install:
    - (cd SDL2-2.0.5 && ./configure && make && sudo make install)

before_script:
    - cd release/

script:
    - how-to-build/linux.sh
    - ./octaspire-maze -h

