language: c

os:
    - linux

dist: trusty
sudo: required

compiler:
    - clang
    - gcc

before_install:
    - sudo add-apt-repository universe
    - sudo apt-get update
    - sudo apt-get install libsdl2-dev -y

before_script:
    - cd release/

script:
    - how-to-build/linux.sh
    - ./octaspire-maze-test-runner

