language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
    - sudo apt-get update -qq
    - sudo apt-get install libsdl2-dev libsdl2-image-dev -y

before_script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DOCTASPIRE_MAZE_COVERAGE:BOOL=ON ..

script:
    - make
    - test/octaspire-maze-test-runner
    - cd test/CMakeFiles/octaspire-maze-test-runner.dir
    - gcov *.gcno

after_success:
      - bash <(curl -s https://codecov.io/bash)

