language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
    - sudo apt-get update -qq
    - sudo apt-get install libsdl2-dev libsdl2-image-dev -y

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - test/octaspire-maze-test-runner

