#ifndef OCTASPIRE_MAZE_INPUT_H
#define OCTASPIRE_MAZE_INPUT_H

typedef enum octaspire_maze_input_t
{
    OCTASPIRE_MAZE_INPUT_NONE,
    OCTASPIRE_MAZE_INPUT_UP,
    OCTASPIRE_MAZE_INPUT_DOWN,
    OCTASPIRE_MAZE_INPUT_LEFT,
    OCTASPIRE_MAZE_INPUT_RIGHT,
    OCTASPIRE_MAZE_INPUT_RESTART,
    OCTASPIRE_MAZE_INPUT_ACTION_1,
    OCTASPIRE_MAZE_INPUT_PREV_LEVEL,
    OCTASPIRE_MAZE_INPUT_NEXT_LEVEL
}
octaspire_maze_input_t;

#endif

